from yacs.config import CfgNode as CN

_C = CN()

# max number of keyframes
_C.BUFFER_SIZE = 2048*2

# bias patch selection towards high gradient regions?
_C.GRADIENT_BIAS = False
# Select between random, gradient, scorer
_C.PATCH_SELECTOR = "scorer"
# Eval mode of patch selector (random, topk, multinomial)
_C.SCORER_EVAL_MODE = "topk"
_C.SCORER_EVAL_USE_GRID = True
# Normalizer (only evs): norm, standard
_C.NORM = "std"

# VO config (increase for better accuracy)
_C.PATCHES_PER_FRAME = 96
_C.REMOVAL_WINDOW = 18
_C.OPTIMIZATION_WINDOW = 10
_C.PATCH_LIFETIME = 9
_C.EDGE_THINNING = False
_C.EDGE_THIN_DENSE_WINDOW = 3
_C.EDGE_THIN_STRIDE = 2
_C.CORR_SINGLE_LEVEL = False

# Active-to-frozen edge marginalization. Frozen edges skip corr/update and keep
# contributing their last target and confidence directly to BA.
_C.ACTIVE_EDGE_MARGINALIZATION = True
_C.MARGINALIZE_WEIGHT_THRESH = 0.6
_C.MARGINALIZE_DELTA_THRESH = 0.35
_C.MARGINALIZE_MIN_AGE = 3
_C.MARGINALIZE_CORE_WINDOW = 3
_C.MARGINALIZE_WEIGHT_DECAY = 0.99
_C.MARGINALIZE_MAX_ACTIVE_EDGES = 3000
_C.MARGINALIZE_ADAPTIVE_BUDGET = False
_C.MARGINALIZE_MIN_ACTIVE_EDGES = 3000
_C.MARGINALIZE_BASE_ACTIVE_EDGES = 3000
_C.MARGINALIZE_HARD_ACTIVE_EDGES = 3000
_C.MARGINALIZE_ADAPT_INTERVAL = 4
_C.MARGINALIZE_ADAPT_MEDIUM_RATIO = 0.10
_C.MARGINALIZE_ADAPT_HARD_RATIO = 0.20
_C.MARGINALIZE_ADAPT_DELTA_THRESH = 0.75
_C.MARGINALIZE_ADAPT_CONF_THRESH = 0.45
_C.MARGINALIZE_ADAPT_MOTION_THRESH = 0.45
_C.MARGINALIZE_ADAPT_HARD_MOTION_THRESH = 0.8
_C.MARGINALIZE_ADAPT_MAX_STEP = 400
_C.MARGINALIZE_MEDIUM_FREEZE_COOLDOWN = 0
_C.MARGINALIZE_HARD_FREEZE_COOLDOWN = 0
_C.WARM_UPDATE_ENABLED = False
_C.WARM_MIN_NEURAL_EDGES = 1800
_C.WARM_BASE_NEURAL_EDGES = 2100
_C.WARM_HARD_NEURAL_EDGES = 2600
_C.WARM_CORE_BONUS = 2.0
_C.WARM_DELTA_WEIGHT = 2.0
_C.WARM_LOWCONF_WEIGHT = 1.0
_C.WARM_STABLE_CONF_THRESH = 0.6
_C.WARM_STABLE_DELTA_THRESH = 0.35
_C.ADAPTIVE_UPDATE_ENABLED = False
_C.ADAPTIVE_FULL_UPDATE_INTERVAL = 2
_C.ADAPTIVE_UPDATE_CORE_WINDOW = 1
_C.ADAPTIVE_UPDATE_DELTA_THRESH = 0.75
_C.ADAPTIVE_UPDATE_CONF_THRESH = 0.45
_C.ADAPTIVE_UPDATE_MIN_EDGES = 1800
_C.COMPILE_UPDATE_NET = False
_C.COMPILE_UPDATE_MODE = 'reduce-overhead'
_C.COMPILE_UPDATE_DYNAMIC = True
_C.COMPILE_UPDATE_FALLBACK = True
_C.SCALAR_SOFTAGG = False
_C.UPDATE_TOPOLOGY_CACHE = True
_C.UPDATE_GPU_TOPOLOGY = True
_C.MARGINALIZE_FORCE_BUDGET = True
_C.MARGINALIZE_USE_FROZEN_IN_BA = True
_C.MARGINALIZE_REFRESH_TARGETS = False
_C.MARGINALIZE_FORCE_DELTA_THRESH = 10.0
_C.MARGINALIZE_FREEZE_DELTA_WEIGHT = 2.0
_C.MARGINALIZE_PROTECT_DELTA_THRESH = 0.0
_C.MARGINALIZE_PROTECT_CONF_THRESH = 0.0
_C.MARGINALIZE_COVERAGE_STRIDE = 0
_C.MARGINALIZE_COVERAGE_PENALTY = 0.0
_C.MARGINALIZE_AGE_WEIGHT = 0.0
_C.MARGINALIZE_BACKBONE_WINDOW = 0
_C.MARGINALIZE_BACKBONE_PENALTY = 0.0
_C.MARGINALIZE_VALIDATE_FROZEN = False
_C.MARGINALIZE_VALIDATE_INTERVAL = 3
_C.MARGINALIZE_SOFT_FROZEN_RESIDUAL = 2.0
_C.MARGINALIZE_MAX_FROZEN_RESIDUAL = 8.0
_C.MARGINALIZE_MIN_FROZEN_WEIGHT_SCALE = 0.2
_C.MARGINALIZE_FROZEN_BA_WEIGHT = 1.0
_C.MARGINALIZE_REACTIVATE_FROZEN = False
_C.MARGINALIZE_REACTIVATE_RESIDUAL = 4.0
_C.MARGINALIZE_MAX_REACTIVATE = 128
_C.MARGINALIZE_REACTIVATE_KEEPALIVE = 2
_C.MARGINALIZE_MAX_FROZEN_EDGES = 6000
_C.MARGINALIZE_PRUNE_INTERVAL = 6
_C.MARGINALIZE_PRINT_STATS = False
_C.BA_ITERATIONS = 6
_C.FINAL_BA_ENABLED = False
_C.FINAL_BA_WINDOW = 0
_C.FINAL_BA_ROUNDS = 2
_C.FINAL_BA_ITERATIONS = 12
_C.TRAJECTORY_SMOOTHING = False
_C.TRAJECTORY_SMOOTHING_ALPHA = 0.15
_C.TRAJECTORY_SMOOTHING_PASSES = 1

# threshold for keyframe removal
_C.KEYFRAME_INDEX = 4
_C.KEYFRAME_THRESH = 12.5

# camera motion model
_C.MOTION_MODEL = 'DAMPED_LINEAR'
_C.MOTION_DAMPING = 0.5

_C.MIXED_PRECISION = True

cfg = _C
